# Setup
title:              Telemetrics
tagline:             'Strategic Advisory'
description:         '  '
url:                 https://hjelliott.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Howard Elliott
  url:              
  email:             howard@telemetrics.com.au

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
